import json
from pathlib import Path
from .config import settings
from .logging_config import get_logger

logger = get_logger("workspace")


class ProjectWorkspace:
    """
    Manages a shared directory for a single plan's generated files.

    Layout:
        outputs/{plan_id}/
            project.json       ← manifest: component name → file path + interface
            storage.py         ← generated by task 0
            api.py             ← generated by task 1 (imports storage.py)
            ...
    """

    def __init__(self, plan_id: str):
        self.plan_id = plan_id
        self.root: Path = settings.OUTPUT_DIR / plan_id
        self.root.mkdir(parents=True, exist_ok=True)

        self._manifest_path = self.root / "project.json"
        self._manifest: dict = {}

        if self._manifest_path.exists():
            try:
                with open(self._manifest_path, "r", encoding="utf-8") as f:
                    self._manifest = json.load(f)
                logger.debug(f"Loaded existing manifest with {len(self._manifest)} entries")
            except (json.JSONDecodeError, OSError) as e:
                logger.warning(f"Failed to load existing manifest: {e} — starting fresh")
                self._manifest = {}
        else:
            logger.info(f"Created workspace at: {self.root}")

    def _write_manifest(self):
        """Persist manifest to project.json."""
        with open(self._manifest_path, "w", encoding="utf-8") as f:
            json.dump(self._manifest, f, indent=2)

    def register_component(
        self,
        name: str,
        file_path: str,
        interface: str,
        depends_on: list[str] = None,
    ):
        """
        Add a component entry to the manifest and persist it.

        Args:
            name:       Component name, e.g. "NoteStorage"
            file_path:  Path relative to workspace root, e.g. "storage.py"
            interface:  Public interface description, e.g. "save(note), load(id)"
            depends_on: Names of components this one imports
        """
        self._manifest[name] = {
            "file_path": file_path,
            "interface": interface,
            "depends_on": depends_on or [],
        }
        self._write_manifest()
        logger.info(f"Registered component: {name} → {file_path}")

    def get_component(self, name: str) -> dict | None:
        """Return the manifest entry for name, or None if not registered."""
        return self._manifest.get(name)

    def get_context_for_task(self, depends_on: list[str]) -> str:
        """
        Build a human-readable context string for the listed dependencies.

        Returns a formatted block like:
            Available components:
            - NoteStorage (outputs/{plan_id}/storage.py): save(note), load(id)
        """
        if not depends_on:
            return ""

        lines = ["Available components:"]
        for name in depends_on:
            entry = self._manifest.get(name)
            if entry:
                abs_path = self.root / entry["file_path"]
                lines.append(
                    f"  - {name} ({abs_path}): {entry['interface']}"
                )
            else:
                logger.debug(f"Component '{name}' not yet in manifest — skipping")

        return "\n".join(lines) if len(lines) > 1 else ""

    def resolve_imports(self, depends_on: list[str]) -> str:
        """
        Return Python import lines for the listed dependencies.

        Uses sys.path injection rather than dotted module paths because plan_id
        is a UUID (contains hyphens and may start with digits — not a valid identifier).

        e.g.:
            import sys
            sys.path.insert(0, r"C:\\...\\outputs\\<plan_id>")
            from storage import NoteStorage
        """
        if not depends_on:
            return ""

        names_to_import = []
        for name in depends_on:
            entry = self._manifest.get(name)
            if entry:
                file_stem = Path(entry["file_path"]).stem
                names_to_import.append((name, file_stem))

        if not names_to_import:
            return ""

        lines = [
            "import sys",
            f"sys.path.insert(0, r\"{self.root}\")",
        ]
        for name, stem in names_to_import:
            lines.append(f"from {stem} import {name}")

        return "\n".join(lines)
